server:
  port: 8092
  servlet:
    context-path: /notification

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 3
          max-interval: 5s
          multiplier: 2
  mail:
    host: smtp.gmail.com
    port: 587
    username: maks.maltsev01@gmail.com
    password: millioner10d
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true